config/routes.rb
Rails.application.routes.draw do

  root 'admins#index'

  resources :admins do
    resources :answers, only: [:new, :index, :create, :show]
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :form
  has_many :answer_contents
  accepts_nested_attributes_for :answer_contents,
                                allow_destroy: true
end

app/models/answer_content.rb
class AnswerContent < ApplicationRecord
  belongs_to :answer
  belongs_to :form_item
  #belongs_to :item_option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_form.rb
class BaseForm
  include ActiveModel::Model
  #include ActiveModel::Validations
  #include ActiveModel::Conversion
  #extend ActiveModel::Naming

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def set_attributes(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def save(form)
    answer = form.answers.build
    form.form_items.each do |item|
      answer.answer_contents.build(
        value: self.send("answer#{item.id}".to_sym),
        form_item_id: item.id
      )
    end
    answer.save!
  end

  # def persisted?
  #   false
  # end
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :form_items, :dependent => :destroy
  accepts_nested_attributes_for :form_items,
                                allow_destroy: true, 
                                reject_if: proc { |attributes| attributes['field'].blank? }
  has_many :answers, :dependent => :destroy
end

app/models/form_item.rb
class FormItem < ApplicationRecord
  belongs_to :form
  #has_many :item_options, :dependent => :destroy
  has_many :answer_contents, :dependent => :destroy
end

app/models/item_option.rb
class ItemOption < ApplicationRecord
  #belongs_to :form_item
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :get_form, only: [:show, :edit, :update, :destroy]

  def index
    @forms = Form.all
  end

  def new
    @form = Form.new
    2.times do
      @form.form_items.build
    end
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @form.destroy
    redirect_to action: :index
  end

  private

  def get_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit(:title, form_items_attributes: [:id, :name, :field, :required])
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :get_form
  before_action :get_answer, only: [:show]

  def index
    @answers = @form.answers
  end

  def new
    @form_items = @form.form_items
    @model = create_model_instance(@form)
  end

  def create
    @model = create_model_instance(@form)
    @model.set_attributes(answer_params)
    if @model.valid?
      @model.save(@form)
      redirect_to action: :index, params: { admin_id: @form.id }
    else
      render action: :new
    end
  end

  def show
  end

  def answer_params
     params.require(:base_form).permit(*column_names(@form))
  end

  def get_form
    @form = Form.find(params[:admin_id])
  end

  def get_answer
    @answer = Answer.find(params[:id])
  end

  def create_model_instance(head)
    form = BaseForm.new
    form_class = form.singleton_class
    form_class.class_eval do
      head.form_items.each do |item|
        answer = "answer#{item.id}".to_sym
        Rails.logger.debug  "#{head.title}のモデルのカラム: #{answer}"
        attr_accessor answer
        if item.required
          validates answer, presence: { message: :blank, value: item.name }
        end
        # if item.maxlength
        #   validates answer, length: { maximum: item.maxlength, value: item.name }
        # end
        # if item.minlength
        #   validates answer, length: { minimum: item.minlength, value: item.name }
        # end
      end
    end
    form
  end

  def column_names(head)
    attrs = []
    head.form_items.each do |item|
      field = "answer#{item.id}".to_sym
      # if item.field == '3'
      #   attrs << { field => [] }
      # else
      attrs << field
      #end
    end
    attrs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admins_helper.rb
module AdminsHelper

  def filed_table
    [
      ['テキスト', '1'],
      ['テキストエリア', '2'],
      #['セレクトボックス', '3'],
    ]
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) +
    link_to("#", { onclick: "remove_fields(this)", class: "btn btn-danger" }) do
      raw(name)
    end
  end

  def link_to_add_fields(name, f, association, target)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to "#", { onclick: %Q[add_fields(this, "#{association}", "#{escape_javascript(fields)}", "#{target}")], class: "btn btn-info" } do
      raw(name)
    end
  end

  
end

app/helpers/answers_helper.rb
module AnswersHelper
  # TODO: viewヘルパーを選べるようにする
  def create_form_field(f, i)
    case i.field
    when "1"
      f.text_field "answer#{i.id}".to_sym
    when "2"
      f.text_area "answer#{i.id}".to_sym
    end
    # when ‘select’
    #   f.select d.title.to_sym, d.category, , :prompt => "選択してください"
    # when ‘checkbox’
    #   d.category.each do |c|
    #     f.check_box d.title.to_sym, {multiple: true}, c[0],nil)
    #   end
    # when 'radio'
    #   d.category.each do |c|
    #     f.radio_button :d.title.to_sym, c[0]
    #     #f.label :d.title.to_sym, c[1], value: index
    #   end
    # when 'text_area'

    #end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/_form_item_fields.html.erb
<div class="fields">
  <%= f.hidden_field :id %>
  名前:<%= f.text_field :name %>
  フィールドの種類:<%= f.select :field, options_for_select(filed_table), { include_blank: true }, { class: "" } %>
  必須:<%= f.check_box :required %>

  <%= link_to_remove_fields "削除<i class='icon-white icon-trash'></i>", f %>
</div>

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/index.html.erb
<h1>管理トップ</h1>

<p><%= link_to '新しい問い合わせフォームを作成する', new_admin_path %></p>

<table>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.title %></td>
        <td><%= link_to 'アンケートに回答する', new_admin_answer_path(admin_id: form.id) %></td>
        <td><%= link_to '回答一覧', admin_answers_path(admin_id: form.id) %></td>
        <td><%= link_to '削除', admin_path(form.id), data: { confirm: '削除していいですか?'}, method: :delete %></td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/new.html.erb
<h1>フォーム作成</h1>
<%= form_for @form, url: '/admins' do |f| %>

  <div class="field">
    タイトル:<%= f.text_field :title %>
  </div>

  <div class="field">
    <div id="form_items">
      <%= f.fields_for :form_items do |lf| %>
        <%= render partial: 'form_item_fields', locals: { f: lf } %>
      <% end %>
    </div>

    <%= link_to_add_fields "<i class='icon-white icon-arrow-right'>追加</i>", f, :form_items, "#form_items" %>
  </div>


  <div>
    <%= f.submit '登録' %>
  </div>

<% end %>

<script type="text/javascript">
  function remove_fields(link) {
    $(link).prev("input[type=hidden]").val("1");
    $(link).closest(".fields").hide();
  }
  function add_fields(link, association, content, target) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    $(target).append(content.replace(regexp, new_id));
  }
</script>

app/views/answers/index.html.erb
<h1><%= @form.title %>の回答一覧</h1>

<table>
  <tbody>
    <%= '回答はありません' if @answers.blank? %>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.name %></td>
        <td><%= answer.created_at %></td>
        <td><%= link_to '詳細', admin_answer_path(admin_id: answer.form.id, id: answer.id) %></td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/answers/new.html.erb
<h1>「<%= @form.title %>」に回答する</h1>

<% if @model.errors.present? %>
  <% @model.errors.messages.each do |k, value| %>
    <% value.each do |v| %>
      <p><%= v %></p>
    <% end %>
  <% end %>
<% end %>

<%= form_for @model, url: admin_answers_path(@form.id) do |f| %>

  <% @form.form_items.each do |i| %>
    <p>
      <%= f.label "answer#{i.id}".to_sym, i.name %>
      <%= create_form_field(f, i) %>
    </p>
  <% end %>
  <%= f.submit 'ほぞん' %>
<% end %>

app/views/answers/show.html.erb
<% @answer.answer_contents.each do |content| %>
  <div>
    <div>
      質問:<%= content.form_item.name %>
    </div>
    <div>
      回答:<%= content.value %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kunibiki7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>